### ISSUE TITLE
Add streaming support for SFTP source

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/sftp#2]
As a user, I'd like to use the streaming support for SFTP source, so I can stream all the file fragments instead of persisting it in the local disk and then transferring. 

**Acceptance:**
- sftp-source is retrofitted to also support streaming capability available in SI 4.3.5 
- test coverage included

**Comment by artembilan** [comment]
The streaming support on the `sink` side isn't possible yet.
See https://jira.spring.io/browse/INT-3746

**Comment by garyrussell** [comment]
@artembilan `(S)FtpRemoteFileTemplate.execute()` supports streaming via `session.write()`; I am not sure what more we would need to do.

**Comment by artembilan** [comment]
The problem that `RemoteFileTemplate.send()` knows nothing about `InputStream`:

```
throw new IllegalArgumentException("Unsupported payload type. The only supported payloads are " +
                            "java.io.File, java.lang.String, and byte[]");
```

I'm not sure how you can utilize `FtpRemoteFileTemplate.execute()` in the `sink`, although `PayloadTypeRouter` may help somehow :smile: 
At least until we come up with the solution in the `FtpRemoteFileTemplate.send()`. 
Maybe it's time to do that and backport to `4.3.x` ?

**Comment by garyrussell** [comment]
@artembilan  I was thnking about something like this...

``` java
@SpringBootApplication
@EnableBinding(Sink.class)
public class FtpstreamoutApplication {

    public static void main(String[] args) {
        SpringApplication.run(FtpstreamoutApplication.class, args);
    }

    @Bean
    public DefaultFtpSessionFactory sf() {
        DefaultFtpSessionFactory sf = new DefaultFtpSessionFactory();
        sf.setHost("10.0.0.3");
        sf.setUsername("ftptest");
        sf.setPassword("ftptest");
        return sf;
    }

    @Bean
    public FtpRemoteFileTemplate remoteFileTemplate() {
        return new FtpRemoteFileTemplate(sf());
    }

    private final Map<String, OutputStream> streams = new ConcurrentHashMap<>();

    @StreamListener(Sink.INPUT)
    public void handle(Message<String> message) throws Exception {
        String file = (String) message.getHeaders().get("file_name");
        if (message.getHeaders().get("control").equals("first")) {
            PipedOutputStream pos = new PipedOutputStream();
            PipedInputStream pis = new PipedInputStream(pos);
            this.streams.put(file, pos);
            Executors.newSingleThreadExecutor().execute(() -> {
                    Boolean result = remoteFileTemplate().execute(s -> {
                        s.write(pis, file);
                        return true;
                    });
                    System.out.println("Sent " + file + ": " + result);
                });
        }
        else {
            this.streams.get(file).write(message.getPayload().getBytes());
            if (message.getHeaders().get("control").equals("last")) {
                this.streams.remove(file).close();
            }
        }
    }

}
```

(with more error checking of course).

**Comment by artembilan** [comment]
Iteresting...
But how is that different from the standard `RemoteFileTemplate.send(Message)`, when `payload` is `byte[]`?

Although I see your point. We add transfer bytes via several messages until `control == last`.
Something similar what we have in the `FileWritingMessageHandler` with its `MessageTriggerAction`.

**Comment by garyrussell** [comment]
Exactly.

**Comment by artembilan** [comment]
Now when we have fixed this, the question is: how about the same for FTP app starter?
Thanks
