### ISSUE TITLE
File Transfer feature should be independent of Task Launch Request

### ISSUE THREAD

**Issue by dturanski** [spring-cloud-stream-app-starters/sftp#27]
Related to #24 Currently the download (transfer) feature is tied to the task launch request. It should also apply to simple transfers.  i.e., if list-only is false and streaming is false and task launch request is 'NONE', this currently copies the file to the local directory and optionally deletes the remote file when complete, etc.  A simple transfer.  This should be harmonized with the new download capability.

**Comment by sabbyanandan** [comment]
This will be addressed via: https://github.com/spring-cloud-stream-app-starters/sftp/pull/32.
