### ISSUE TITLE
Sftp Polling frequency configuration is ignored

### ISSUE THREAD

**Issue by dturanski** [spring-cloud-stream-app-starters/sftp#28]
Could be this: 
```The `TriggerPropertiesMaxMessagesDefaultUnlimited` is a `@ConfigurationProperties`
but it is used in the `@Import` on the `SftpSourceConfiguration` instead of the `@EnableConfigurationProperties```

Fixes #32.

**Comment by dturanski** [comment]
FIxed by https://github.com/spring-cloud-stream-app-starters/sftp/pull/32

**Comment by sabbyanandan** [comment]
Closing in favor of #32.
