### ISSUE TITLE
[sftp-dataflow-source] Add support to launch Tasks dynamically

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/sftp#60]
As a user, I'd like to have the option to dynamically launch tasks in `DataFlowTaskLaunchRequest`, so I can assign a different "task name" for each of the consumed SFTP payloads.

Notes: 

- This requires changes to `RotatingServerAdvice` and `StandardRotationPolicy` in SI to extend it in `sftp-dataflow` to then add support for it.
- Once that is added to SI, we will inherit the upstream changes to redesign the `sftp-dataflow` application to optionally also configure and pin each payload to a particular Task.

**Comment by dturanski** [comment]
Currently on hold until we upgrade app starters to Spring and SI 5.2 since the required SI change is considered a breaking change for SI 5.1.  https://github.com/spring-projects/spring-integration/pull/3028#discussion_r314329893
